### ISSUE TITLE
Include Python Source

### ISSUE THREAD

**Issue by jimp02** [mhoumann/CommentsPlus#1]
I would like to see Python source included in this extension.

**Comment by mhoumann** [comment]
Are you using the PTVS Python extension?
What I'm seeing is that with the extension enabled, CommentsPlus also works for python source.

**Comment by jimp02** [comment]
It seems to be working OK now.
I am getting an error when I load a python program but
it seems to be unrelated to Comments Plus.

**Comment by mhoumann** [comment]
OK. I'll close this issue, then.
