### ISSUE TITLE
Does not work with .js files

### ISSUE THREAD

**Issue by VooVoo01** [mhoumann/CommentsPlus#19]
VS 17.3.3
CommentsPlus17 1.10.0
Works fine with .html and .php

**But does not work with .js files.**
What could be the problem?

**Comment by mhoumann** [comment]
Hmm. So italics looks fine in my install.
But comment tags appear to be broken. I'll see if I can figure it out, when I get a moment.

**Comment by mhoumann** [comment]
Working OK with VS 17.8 for me
