### ISSUE TITLE
unable to set the collor

### ISSUE THREAD

**Issue by PGTBoos** [mhoumann/CommentsPlus#22]
with vs2022 i dont see any settings.
 Also i'm using a dark theme, idealy i would like to set the font color and background for certain keywords i define
 the ? ! ?! is okay but //todo and //bug i like to set their collors to something that pops a bit more.
 As on the theme i use it doesnt realy pop.

**Comment by mhoumann** [comment]
Go to Tools menu -> Options ->Fonts and Colors
Find Comment - <whatnot> lines.
You should be able to configure color.

<img width="572" alt="image" src="https://github.com/mhoumann/CommentsPlus/assets/6515223/56cb30a7-9866-4879-8650-b2f55df57b15">
