### ISSUE TITLE
Add whitespace between // and letters (//<space>TODO)

### ISSUE THREAD

**Issue by dirondin** [mhoumann/CommentsPlus#4]
Hello.

It would be great if you add whitespace charactrer support in regex of `// TODO` template.
And add some other rules like `// XXX` or `// FIXME` or add support for configuring these templates.

**Comment by mhoumann** [comment]
Thanks for the suggestion.
If I can find a good, simple way to do this without allocations* - and find the time, I'll consider adding something like this.

*) The code is constantly running in the editor, so it's quite performance/allocation sensitive  (regex is very heavy in this regard) ...

**Comment by warrenlbrown** [comment]
Ditto!

**Comment by mhoumann** [comment]
Version 1.8.2 now supports a leading whitespace.
